# Generated by Django 3.2.9 on 2021-11-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_auto_20211117_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
    ]
